import { z } from "zod";

export const terrainSettingsSchema = z.object({
  scene: z.enum(["landscape", "one-hill", "two-hills"]).default("landscape"),
  tilt: z.number().min(10).max(85).default(25.1),
  rotation: z.number().min(-180).max(180).default(31.8),
  zoom: z.number().min(0.25).max(3).default(0.95),
  extent: z.number().min(1).max(3).default(1.9),
  elevation: z.number().min(0.15).max(3).default(0.5),
  peaks: z.number().min(0).max(2).default(1.6),
  spread: z.number().min(0.6).max(4).default(1.6),
  depth: z.number().min(0.6).max(4).default(1.6),
  speed: z.number().min(0).max(1).default(0.04),
  terrainMotion: z.boolean().default(true),
  evolution: z.number().min(0).max(3).default(3),
  shimmer: z.number().min(0).max(2).default(2),
  trail: z.number().min(0).max(1).default(1),
  trailWidth: z.number().min(1).max(6).default(3),
  trailLift: z.number().min(0).max(0.15).default(0.05),
  routeMaxSpeed: z.number().min(0.1).max(5).default(0.3),
  checkpointMotion: z.boolean().default(true),
  checkpointSpeed: z.number().min(0.1).max(3).default(1),
  checkpointDrift: z.number().min(0).max(2).default(0.65),
  checkpointAvoidance: z.boolean().default(true),
  contrast: z.number().min(0.1).max(1).default(0.1),
  stepHeight: z.number().min(0.04).max(0.3).default(0.13),
  offsetX: z.number().min(-1).max(1).default(0.58),
  offsetY: z.number().min(-1).max(1).default(0.16),
  fade: z.number().min(0).max(1).default(0.3),
  quality: z.enum(["auto", "low", "high"]).default("auto"),
});

export type TerrainSettings = z.infer<typeof terrainSettingsSchema>;
export const terrainSceneIndex = { landscape: 0, "one-hill": 1, "two-hills": 2 };
export const defaultTerrainSettings = terrainSettingsSchema.parse({});
export const routeExperimentSettings: TerrainSettings = {
  ...defaultTerrainSettings,
  scene: "one-hill",
  trail: 1,
  checkpointMotion: false,
  checkpointDrift: 0,
  checkpointAvoidance: false,
  terrainMotion: false,
  tilt: 55,
  rotation: 0,
  zoom: 1.1,
  extent: 1,
  elevation: 0.8,
  peaks: 1,
  spread: 1,
  depth: 1,
  offsetX: 0,
  offsetY: -0.1,
  fade: 0,
  shimmer: 0,
};
export const terrainPresets = [
  { name: "Default", settings: defaultTerrainSettings },
  { name: "One hill · 2 points", settings: routeExperimentSettings },
  {
    name: "Two hills · 2 points",
    settings: { ...routeExperimentSettings, scene: "two-hills" },
  },
  {
    name: "Overhead",
    settings: {
      ...defaultTerrainSettings,
      tilt: 76,
      rotation: -20,
      zoom: 0.8,
      elevation: 0.65,
      offsetX: 0,
      offsetY: -0.12,
      fade: 0,
    },
  },
  {
    name: "Open landscape",
    settings: {
      ...defaultTerrainSettings,
      tilt: 26.6,
      rotation: -4.3,
      zoom: 1.65,
      elevation: 0.4,
      peaks: 1.2,
      spread: 1.6,
      depth: 1.6,
      speed: 0.1,
      evolution: 2,
      shimmer: 2,
      contrast: 1,
      stepHeight: 0.09,
      offsetX: 0,
      offsetY: -0.12,
      fade: 0,
    },
  },
] satisfies { name: string; settings: TerrainSettings }[];
