/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as CreditHistoryRouteImport } from './routes/credit-history'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TerrainRouteImport } from './routes/terrain'
import { Route as HandoffSessionIdRouteImport } from './routes/handoff.$sessionId'
import { Route as ScoutsIndexRouteImport } from './routes/scouts.index'
import { Route as ScoutsSlugRouteImport } from './routes/scouts.$slug'
import { Route as SitesSiteRouteImport } from './routes/sites.$site'
import { Route as TasksThreadRouteImport } from './routes/tasks.$thread'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditHistoryRoute = CreditHistoryRouteImport.update({
  id: '/credit-history',
  path: '/credit-history',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TerrainRoute = TerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffSessionIdRoute = HandoffSessionIdRouteImport.update({
  id: '/handoff/$sessionId',
  path: '/handoff/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsIndexRoute = ScoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoutsRoute,
} as any)
const ScoutsSlugRoute = ScoutsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScoutsRoute,
} as any)
const SitesSiteRoute = SitesSiteRouteImport.update({
  id: '/sites/$site',
  path: '/sites/$site',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksThreadRoute = TasksThreadRouteImport.update({
  id: '/tasks/$thread',
  path: '/tasks/$thread',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/credit-history': typeof CreditHistoryRoute
  '/lab': typeof LabRoute
  '/members': typeof MembersRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/terrain': typeof TerrainRoute
  '/handoff/$sessionId': typeof HandoffSessionIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/sites/$site': typeof SitesSiteRoute
  '/tasks/$thread': typeof TasksThreadRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/credit-history': typeof CreditHistoryRoute
  '/lab': typeof LabRoute
  '/members': typeof MembersRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/terrain': typeof TerrainRoute
  '/handoff/$sessionId': typeof HandoffSessionIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/sites/$site': typeof SitesSiteRoute
  '/tasks/$thread': typeof TasksThreadRoute
  '/scouts': typeof ScoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/credit-history': typeof CreditHistoryRoute
  '/lab': typeof LabRoute
  '/members': typeof MembersRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/terrain': typeof TerrainRoute
  '/handoff/$sessionId': typeof HandoffSessionIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/sites/$site': typeof SitesSiteRoute
  '/tasks/$thread': typeof TasksThreadRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account-deletion'
    | '/credit-history'
    | '/lab'
    | '/members'
    | '/play'
    | '/privacy'
    | '/scouts'
    | '/settings'
    | '/terms'
    | '/terrain'
    | '/handoff/$sessionId'
    | '/scouts/$slug'
    | '/sites/$site'
    | '/tasks/$thread'
    | '/scouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account-deletion'
    | '/credit-history'
    | '/lab'
    | '/members'
    | '/play'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/terrain'
    | '/handoff/$sessionId'
    | '/scouts/$slug'
    | '/sites/$site'
    | '/tasks/$thread'
    | '/scouts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account-deletion'
    | '/credit-history'
    | '/lab'
    | '/members'
    | '/play'
    | '/privacy'
    | '/scouts'
    | '/settings'
    | '/terms'
    | '/terrain'
    | '/handoff/$sessionId'
    | '/scouts/$slug'
    | '/sites/$site'
    | '/tasks/$thread'
    | '/scouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  CreditHistoryRoute: typeof CreditHistoryRoute
  LabRoute: typeof LabRoute
  MembersRoute: typeof MembersRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  ScoutsRoute: typeof ScoutsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TerrainRoute: typeof TerrainRoute
  HandoffSessionIdRoute: typeof HandoffSessionIdRoute
  SitesSiteRoute: typeof SitesSiteRoute
  TasksThreadRoute: typeof TasksThreadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-history': {
      id: '/credit-history'
      path: '/credit-history'
      fullPath: '/credit-history'
      preLoaderRoute: typeof CreditHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terrain': {
      id: '/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof TerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$sessionId': {
      id: '/handoff/$sessionId'
      path: '/handoff/$sessionId'
      fullPath: '/handoff/$sessionId'
      preLoaderRoute: typeof HandoffSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/': {
      id: '/scouts/'
      path: '/'
      fullPath: '/scouts/'
      preLoaderRoute: typeof ScoutsIndexRouteImport
      parentRoute: typeof ScoutsRoute
    }
    '/scouts/$slug': {
      id: '/scouts/$slug'
      path: '/$slug'
      fullPath: '/scouts/$slug'
      preLoaderRoute: typeof ScoutsSlugRouteImport
      parentRoute: typeof ScoutsRoute
    }
    '/sites/$site': {
      id: '/sites/$site'
      path: '/sites/$site'
      fullPath: '/sites/$site'
      preLoaderRoute: typeof SitesSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$thread': {
      id: '/tasks/$thread'
      path: '/tasks/$thread'
      fullPath: '/tasks/$thread'
      preLoaderRoute: typeof TasksThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScoutsRouteChildren {
  ScoutsSlugRoute: typeof ScoutsSlugRoute
  ScoutsIndexRoute: typeof ScoutsIndexRoute
}

const ScoutsRouteChildren: ScoutsRouteChildren = {
  ScoutsSlugRoute: ScoutsSlugRoute,
  ScoutsIndexRoute: ScoutsIndexRoute,
}

const ScoutsRouteWithChildren =
  ScoutsRoute._addFileChildren(ScoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  CreditHistoryRoute: CreditHistoryRoute,
  LabRoute: LabRoute,
  MembersRoute: MembersRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  ScoutsRoute: ScoutsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TerrainRoute: TerrainRoute,
  HandoffSessionIdRoute: HandoffSessionIdRoute,
  SitesSiteRoute: SitesSiteRoute,
  TasksThreadRoute: TasksThreadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
