/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HandoffHandoffIdRouteImport } from './routes/handoff.$handoffId'
import { Route as ScoutsIndexRouteImport } from './routes/scouts.index'
import { Route as ScoutsSlugRouteImport } from './routes/scouts.$slug'
import { Route as SitesSiteRouteImport } from './routes/sites.$site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffHandoffIdRoute = HandoffHandoffIdRouteImport.update({
  id: '/handoff/$handoffId',
  path: '/handoff/$handoffId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsIndexRoute = ScoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoutsRoute,
} as any)
const ScoutsSlugRoute = ScoutsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScoutsRoute,
} as any)
const SitesSiteRoute = SitesSiteRouteImport.update({
  id: '/sites/$site',
  path: '/sites/$site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/agents': typeof AgentsRoute
  '/chats': typeof ChatsRoute
  '/members': typeof MembersRoute
  '/play': typeof PlayRoute
  '/review': typeof ReviewRoute
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/sites/$site': typeof SitesSiteRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/agents': typeof AgentsRoute
  '/chats': typeof ChatsRoute
  '/members': typeof MembersRoute
  '/play': typeof PlayRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/sites/$site': typeof SitesSiteRoute
  '/scouts': typeof ScoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/agents': typeof AgentsRoute
  '/chats': typeof ChatsRoute
  '/members': typeof MembersRoute
  '/play': typeof PlayRoute
  '/review': typeof ReviewRoute
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/sites/$site': typeof SitesSiteRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/agents'
    | '/chats'
    | '/members'
    | '/play'
    | '/review'
    | '/scouts'
    | '/settings'
    | '/handoff/$handoffId'
    | '/scouts/$slug'
    | '/sites/$site'
    | '/scouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/agents'
    | '/chats'
    | '/members'
    | '/play'
    | '/review'
    | '/settings'
    | '/handoff/$handoffId'
    | '/scouts/$slug'
    | '/sites/$site'
    | '/scouts'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/agents'
    | '/chats'
    | '/members'
    | '/play'
    | '/review'
    | '/scouts'
    | '/settings'
    | '/handoff/$handoffId'
    | '/scouts/$slug'
    | '/sites/$site'
    | '/scouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  AgentsRoute: typeof AgentsRoute
  ChatsRoute: typeof ChatsRoute
  MembersRoute: typeof MembersRoute
  PlayRoute: typeof PlayRoute
  ReviewRoute: typeof ReviewRoute
  ScoutsRoute: typeof ScoutsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  HandoffHandoffIdRoute: typeof HandoffHandoffIdRoute
  SitesSiteRoute: typeof SitesSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$handoffId': {
      id: '/handoff/$handoffId'
      path: '/handoff/$handoffId'
      fullPath: '/handoff/$handoffId'
      preLoaderRoute: typeof HandoffHandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/': {
      id: '/scouts/'
      path: '/'
      fullPath: '/scouts/'
      preLoaderRoute: typeof ScoutsIndexRouteImport
      parentRoute: typeof ScoutsRoute
    }
    '/scouts/$slug': {
      id: '/scouts/$slug'
      path: '/$slug'
      fullPath: '/scouts/$slug'
      preLoaderRoute: typeof ScoutsSlugRouteImport
      parentRoute: typeof ScoutsRoute
    }
    '/sites/$site': {
      id: '/sites/$site'
      path: '/sites/$site'
      fullPath: '/sites/$site'
      preLoaderRoute: typeof SitesSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScoutsRouteChildren {
  ScoutsSlugRoute: typeof ScoutsSlugRoute
  ScoutsIndexRoute: typeof ScoutsIndexRoute
}

const ScoutsRouteChildren: ScoutsRouteChildren = {
  ScoutsSlugRoute: ScoutsSlugRoute,
  ScoutsIndexRoute: ScoutsIndexRoute,
}

const ScoutsRouteWithChildren =
  ScoutsRoute._addFileChildren(ScoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  AgentsRoute: AgentsRoute,
  ChatsRoute: ChatsRoute,
  MembersRoute: MembersRoute,
  PlayRoute: PlayRoute,
  ReviewRoute: ReviewRoute,
  ScoutsRoute: ScoutsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  HandoffHandoffIdRoute: HandoffHandoffIdRoute,
  SitesSiteRoute: SitesSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
