/// <reference types="node" />
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

import { prerenderPathRewrites, type PrerenderPathRewrites } from "../prerender.config.ts";

export const generatedRedirectsStartTag = "# @samebase/app-prerender-redirects:start";
export const generatedRedirectsEndTag = "# @samebase/app-prerender-redirects:end";

const redirectsFilePath = path.resolve("public/_redirects");

export function buildGeneratedRedirects(rewrites: PrerenderPathRewrites) {
  const aliasesByOutputPath = new Map<string, string[]>();

  for (const [alias, outputPath] of Object.entries(rewrites)) {
    const aliases = aliasesByOutputPath.get(outputPath) ?? [];
    aliases.push(`${alias} ${outputPath} 200`);
    aliasesByOutputPath.set(outputPath, aliases);
  }

  const redirectGroups = [...aliasesByOutputPath.values()].map((aliases) => aliases.join("\n"));

  return [
    "# Generated by vp run generate:cloudflare-redirects.",
    "# Cloudflare SPA mode serves /index.html for unknown app routes, so",
    "# the SPA shell owns that file. These exact aliases expose prerendered",
    "# public pages without catching hashed assets.",
    "",
    redirectGroups.join("\n\n"),
  ].join("\n");
}

function findMarkerLine(args: { lines: readonly string[]; marker: string }) {
  let markerLine: number | null = null;

  for (const [index, line] of args.lines.entries()) {
    if (line.trim() !== args.marker) {
      continue;
    }
    if (markerLine !== null) {
      throw new Error(`Expected exactly one ${args.marker} marker in public/_redirects.`);
    }

    markerLine = index;
  }

  if (markerLine === null) {
    throw new Error(`Missing ${args.marker} marker in public/_redirects.`);
  }

  return markerLine;
}

export function replaceGeneratedRedirectsBlock(contents: string, generatedRedirects: string) {
  const normalizedContents = contents.replace(/\r\n/g, "\n");
  const lines = normalizedContents.split("\n");
  const startLine = findMarkerLine({ lines, marker: generatedRedirectsStartTag });
  const endLine = findMarkerLine({ lines, marker: generatedRedirectsEndTag });

  if (startLine >= endLine) {
    throw new Error("The Cloudflare redirects start marker must come before the end marker.");
  }

  const nextContents = [
    ...lines.slice(0, startLine + 1),
    ...generatedRedirects.split("\n"),
    ...lines.slice(endLine),
  ].join("\n");

  return nextContents.endsWith("\n") ? nextContents : `${nextContents}\n`;
}

export function updateRedirectsFile(filePath = redirectsFilePath) {
  const contents = readFileSync(filePath, "utf8");
  const generatedRedirects = buildGeneratedRedirects(prerenderPathRewrites);
  const nextContents = replaceGeneratedRedirectsBlock(contents, generatedRedirects);

  if (nextContents === contents) {
    return;
  }

  writeFileSync(filePath, nextContents, "utf8");
}

const entrypoint = process.argv[1];
if (entrypoint && import.meta.url === pathToFileURL(entrypoint).href) {
  updateRedirectsFile();
}
