import { describe, expect, it } from "vite-plus/test";

import {
  createPrerenderPathRewrites,
  prerenderPathRewrites,
  rewritePrerenderPath,
} from "../prerender.config.ts";
import {
  buildGeneratedRedirects,
  generatedRedirectsEndTag,
  generatedRedirectsStartTag,
  replaceGeneratedRedirectsBlock,
} from "./generate-cloudflare-redirects.ts";

describe("generate-cloudflare-redirects", () => {
  it("creates exact aliases from public prerender pages", () => {
    expect(buildGeneratedRedirects(prerenderPathRewrites)).toBe(
      [
        "# Generated by vp run generate:cloudflare-redirects.",
        "# Cloudflare SPA mode serves /index.html for unknown app routes, so",
        "# the SPA shell owns that file. These exact aliases expose prerendered",
        "# public pages without catching hashed assets.",
        "",
        "/ /_landing.html 200",
        "",
        "/about /about/index.html 200",
        "/about/ /about/index.html 200",
        "/about/index.html /about/index.html 200",
      ].join("\n"),
    );
  });

  it("replaces only the tagged generated block", () => {
    const contents = [
      "/legacy /new 301",
      generatedRedirectsStartTag,
      "/old /old.html 200",
      generatedRedirectsEndTag,
      "/external https://example.com 302",
      "",
    ].join("\n");

    expect(
      replaceGeneratedRedirectsBlock(contents, buildGeneratedRedirects(prerenderPathRewrites)),
    ).toBe(
      [
        "/legacy /new 301",
        generatedRedirectsStartTag,
        "# Generated by vp run generate:cloudflare-redirects.",
        "# Cloudflare SPA mode serves /index.html for unknown app routes, so",
        "# the SPA shell owns that file. These exact aliases expose prerendered",
        "# public pages without catching hashed assets.",
        "",
        "/ /_landing.html 200",
        "",
        "/about /about/index.html 200",
        "/about/ /about/index.html 200",
        "/about/index.html /about/index.html 200",
        generatedRedirectsEndTag,
        "/external https://example.com 302",
        "",
      ].join("\n"),
    );
  });

  it("requires the generated block tags", () => {
    expect(() => replaceGeneratedRedirectsBlock("/ /_landing.html 200\n", "")).toThrow(
      "Missing # @samebase/app-prerender-redirects:start",
    );
  });

  it("uses the same aliases for Convex path rewrites", () => {
    expect(prerenderPathRewrites).toEqual({
      "/": "/_landing.html",
      "/about": "/about/index.html",
      "/about/": "/about/index.html",
      "/about/index.html": "/about/index.html",
    });
    expect(rewritePrerenderPath("/")).toBe("/_landing.html");
    expect(rewritePrerenderPath("/about/")).toBe("/about/index.html");
    expect(rewritePrerenderPath("/lists/abc")).toBe("/lists/abc");
  });

  it("keeps SPA shell ownership of /index.html", () => {
    expect(() =>
      createPrerenderPathRewrites([
        {
          path: "/",
          prerender: {
            enabled: true,
            outputPath: "/index.html",
          },
        },
      ]),
    ).toThrow("SPA shell serves that file");
  });
});
