/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HandoffHandoffIdRouteImport } from './routes/handoff.$handoffId'
import { Route as ScoutsIndexRouteImport } from './routes/scouts.index'
import { Route as ScoutsSlugRouteImport } from './routes/scouts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffHandoffIdRoute = HandoffHandoffIdRouteImport.update({
  id: '/handoff/$handoffId',
  path: '/handoff/$handoffId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsIndexRoute = ScoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoutsRoute,
} as any)
const ScoutsSlugRoute = ScoutsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/settings': typeof SettingsRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/scouts': typeof ScoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/scouts'
    | '/settings'
    | '/handoff/$handoffId'
    | '/scouts/$slug'
    | '/scouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/settings'
    | '/handoff/$handoffId'
    | '/scouts/$slug'
    | '/scouts'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/scouts'
    | '/settings'
    | '/handoff/$handoffId'
    | '/scouts/$slug'
    | '/scouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  ScoutsRoute: typeof ScoutsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  HandoffHandoffIdRoute: typeof HandoffHandoffIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$handoffId': {
      id: '/handoff/$handoffId'
      path: '/handoff/$handoffId'
      fullPath: '/handoff/$handoffId'
      preLoaderRoute: typeof HandoffHandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/': {
      id: '/scouts/'
      path: '/'
      fullPath: '/scouts/'
      preLoaderRoute: typeof ScoutsIndexRouteImport
      parentRoute: typeof ScoutsRoute
    }
    '/scouts/$slug': {
      id: '/scouts/$slug'
      path: '/$slug'
      fullPath: '/scouts/$slug'
      preLoaderRoute: typeof ScoutsSlugRouteImport
      parentRoute: typeof ScoutsRoute
    }
  }
}

interface ScoutsRouteChildren {
  ScoutsSlugRoute: typeof ScoutsSlugRoute
  ScoutsIndexRoute: typeof ScoutsIndexRoute
}

const ScoutsRouteChildren: ScoutsRouteChildren = {
  ScoutsSlugRoute: ScoutsSlugRoute,
  ScoutsIndexRoute: ScoutsIndexRoute,
}

const ScoutsRouteWithChildren =
  ScoutsRoute._addFileChildren(ScoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  ScoutsRoute: ScoutsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  HandoffHandoffIdRoute: HandoffHandoffIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
