/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ScoutsIndexRouteImport } from './routes/scouts.index'
import { Route as ScoutsSlugRouteImport } from './routes/scouts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ScoutsIndexRoute = ScoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoutsRoute,
} as any)
const ScoutsSlugRoute = ScoutsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/products': typeof ProductsRouteWithChildren
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/settings': typeof SettingsRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/scouts': typeof ScoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/products': typeof ProductsRouteWithChildren
  '/scouts': typeof ScoutsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/scouts/$slug': typeof ScoutsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/products'
    | '/scouts'
    | '/settings'
    | '/scouts/$slug'
    | '/products/'
    | '/scouts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lab' | '/settings' | '/scouts/$slug' | '/products' | '/scouts'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/products'
    | '/scouts'
    | '/settings'
    | '/scouts/$slug'
    | '/products/'
    | '/scouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ScoutsRoute: typeof ScoutsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/scouts/': {
      id: '/scouts/'
      path: '/'
      fullPath: '/scouts/'
      preLoaderRoute: typeof ScoutsIndexRouteImport
      parentRoute: typeof ScoutsRoute
    }
    '/scouts/$slug': {
      id: '/scouts/$slug'
      path: '/$slug'
      fullPath: '/scouts/$slug'
      preLoaderRoute: typeof ScoutsSlugRouteImport
      parentRoute: typeof ScoutsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ScoutsRouteChildren {
  ScoutsSlugRoute: typeof ScoutsSlugRoute
  ScoutsIndexRoute: typeof ScoutsIndexRoute
}

const ScoutsRouteChildren: ScoutsRouteChildren = {
  ScoutsSlugRoute: ScoutsSlugRoute,
  ScoutsIndexRoute: ScoutsIndexRoute,
}

const ScoutsRouteWithChildren =
  ScoutsRoute._addFileChildren(ScoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ScoutsRoute: ScoutsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
